// import { Geist, Geist_Mono, Lato } from "next/font/google";
// import "./globals.css";
// import Provider from "@/provider/Provider";
// import { Toaster } from "react-hot-toast";
// import Navbar from "@/components/Navbar";
// import SiteFooter from "@/components/SiteFooter";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const lato = Lato({
//   subsets: ["latin"],
//   weight: ["300", "400", "700"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <Provider>
//           <Toaster />
//           <Navbar />
//           {children}
//           <SiteFooter />
//         </Provider>
//       </body>
//     </html>
//   );
// }
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import SiteFooter from "@/components/SiteFooter";
import AllProvider from "@/provider/AllProvider";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter", // Define as CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
    
      <AllProvider>

            <Toaster />
          <Navbar />
          {children}
          <SiteFooter />

      </AllProvider>
      </body>
    </html>
  );
}