import { Geist, Geist_Mono, Lato } from "next/font/google";
import Provider from "@/provider/Provider";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import SiteFooter from "@/components/SiteFooter";
import Sidebar from "@/components/dashboard/Sidebar";
import Topbar from "@/components/dashboard/Topbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        
      <Provider>
        <Toaster/>

   <div className="flex ">


   <section>
             <Sidebar/>
   </section>

            


         <section className="flex-1 ">

            <Topbar/>
              {children}


         </section>
   </div>
   
        
             
      </Provider>
        
        </body>
    </html>
  );
}
